import dotenv from 'dotenv';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const envPath = path.join(__dirname, '../.env');

// Load environment variables from .env file
if (fs.existsSync(envPath)) {
  dotenv.config({ path: envPath });
}

// Generate a small browser-friendly JS file that injects the key into `window`.
// This file (`scripts/env-config.js`) will be included in `index.html` before
// other client scripts so browser code can read `window.__GOOGLE_MAPS_API_KEY__`.

const outPath = path.join(__dirname, 'env-config.js');
const publicOutPath = path.join(__dirname, '../public/scripts/env-config.js');
const apiKey = process.env.VITE_GOOGLE_MAPS_API_KEY || '';
const outContent = `// This file is auto-generated by scripts/load-env.js
// Do not commit sensitive values. .env is git-ignored.
window.__GOOGLE_MAPS_API_KEY__ = ${apiKey ? JSON.stringify(apiKey) : 'null'};
window.__APP_CONFIG__ = { VITE_GOOGLE_MAPS_API_KEY: ${apiKey ? JSON.stringify(apiKey) : 'null'} };
window.apiKey = window.__GOOGLE_MAPS_API_KEY__;
`;

try {
  fs.writeFileSync(outPath, outContent, { encoding: 'utf8' });
  console.log('Wrote env config to', outPath);
  
  // Also write to public folder for Vite build
  fs.writeFileSync(publicOutPath, outContent, { encoding: 'utf8' });
  console.log('Wrote env config to', publicOutPath);
} catch (err) {
  console.error('Failed to write env-config.js:', err);
}

export default process.env;
